//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhm.Web.IbusService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IbuData", Namespace="http://schemas.datacontract.org/2004/07/Ibus")]
    [System.SerializableAttribute()]
    public partial class IbuData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string alamatIbuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idIbuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string namaIbuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pkjIbuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime tlIbuField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string alamatIbu {
            get {
                return this.alamatIbuField;
            }
            set {
                if ((object.ReferenceEquals(this.alamatIbuField, value) != true)) {
                    this.alamatIbuField = value;
                    this.RaisePropertyChanged("alamatIbu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idIbu {
            get {
                return this.idIbuField;
            }
            set {
                if ((this.idIbuField.Equals(value) != true)) {
                    this.idIbuField = value;
                    this.RaisePropertyChanged("idIbu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string namaIbu {
            get {
                return this.namaIbuField;
            }
            set {
                if ((object.ReferenceEquals(this.namaIbuField, value) != true)) {
                    this.namaIbuField = value;
                    this.RaisePropertyChanged("namaIbu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pkjIbu {
            get {
                return this.pkjIbuField;
            }
            set {
                if ((object.ReferenceEquals(this.pkjIbuField, value) != true)) {
                    this.pkjIbuField = value;
                    this.RaisePropertyChanged("pkjIbu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime tlIbu {
            get {
                return this.tlIbuField;
            }
            set {
                if ((this.tlIbuField.Equals(value) != true)) {
                    this.tlIbuField = value;
                    this.RaisePropertyChanged("tlIbu");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IbusService.IIbusService")]
    public interface IIbusService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIbusService/InsertIbu", ReplyAction="http://tempuri.org/IIbusService/InsertIbuResponse")]
        void InsertIbu(string nama, string pkj, System.DateTime tl, string alamat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIbusService/GetIbuById", ReplyAction="http://tempuri.org/IIbusService/GetIbuByIdResponse")]
        Bhm.Web.IbusService.IbuData GetIbuById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIbusService/GetIdByName", ReplyAction="http://tempuri.org/IIbusService/GetIdByNameResponse")]
        int GetIdByName(string nama);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIbusServiceChannel : Bhm.Web.IbusService.IIbusService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IbusServiceClient : System.ServiceModel.ClientBase<Bhm.Web.IbusService.IIbusService>, Bhm.Web.IbusService.IIbusService {
        
        public IbusServiceClient() {
        }
        
        public IbusServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IbusServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IbusServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IbusServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void InsertIbu(string nama, string pkj, System.DateTime tl, string alamat) {
            base.Channel.InsertIbu(nama, pkj, tl, alamat);
        }
        
        public Bhm.Web.IbusService.IbuData GetIbuById(int id) {
            return base.Channel.GetIbuById(id);
        }
        
        public int GetIdByName(string nama) {
            return base.Channel.GetIdByName(nama);
        }
    }
}
