//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhm.Web.KegiatansService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KegiatansService.IKegiatansService")]
    public interface IKegiatansService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKegiatansService/InsertKegiatan", ReplyAction="http://tempuri.org/IKegiatansService/InsertKegiatanResponse")]
        void InsertKegiatan(int idBalita, int idPosyandu, System.DateTime tgl, double bb, double tb);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IKegiatansServiceChannel : Bhm.Web.KegiatansService.IKegiatansService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KegiatansServiceClient : System.ServiceModel.ClientBase<Bhm.Web.KegiatansService.IKegiatansService>, Bhm.Web.KegiatansService.IKegiatansService {
        
        public KegiatansServiceClient() {
        }
        
        public KegiatansServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KegiatansServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KegiatansServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KegiatansServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void InsertKegiatan(int idBalita, int idPosyandu, System.DateTime tgl, double bb, double tb) {
            base.Channel.InsertKegiatan(idBalita, idPosyandu, tgl, bb, tb);
        }
    }
}
