//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhm.Web.AyahsService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AyahData", Namespace="http://schemas.datacontract.org/2004/07/Ayahs")]
    [System.SerializableAttribute()]
    public partial class AyahData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string alamatAyahField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idAyahField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string namaAyahField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pkjAyahField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime tlAyahField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string alamatAyah {
            get {
                return this.alamatAyahField;
            }
            set {
                if ((object.ReferenceEquals(this.alamatAyahField, value) != true)) {
                    this.alamatAyahField = value;
                    this.RaisePropertyChanged("alamatAyah");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idAyah {
            get {
                return this.idAyahField;
            }
            set {
                if ((this.idAyahField.Equals(value) != true)) {
                    this.idAyahField = value;
                    this.RaisePropertyChanged("idAyah");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string namaAyah {
            get {
                return this.namaAyahField;
            }
            set {
                if ((object.ReferenceEquals(this.namaAyahField, value) != true)) {
                    this.namaAyahField = value;
                    this.RaisePropertyChanged("namaAyah");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pkjAyah {
            get {
                return this.pkjAyahField;
            }
            set {
                if ((object.ReferenceEquals(this.pkjAyahField, value) != true)) {
                    this.pkjAyahField = value;
                    this.RaisePropertyChanged("pkjAyah");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime tlAyah {
            get {
                return this.tlAyahField;
            }
            set {
                if ((this.tlAyahField.Equals(value) != true)) {
                    this.tlAyahField = value;
                    this.RaisePropertyChanged("tlAyah");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AyahsService.IAyahsService")]
    public interface IAyahsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAyahsService/InsertAyah", ReplyAction="http://tempuri.org/IAyahsService/InsertAyahResponse")]
        void InsertAyah(string nama, string pkj, System.DateTime tl, string alamat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAyahsService/GetAyahById", ReplyAction="http://tempuri.org/IAyahsService/GetAyahByIdResponse")]
        Bhm.Web.AyahsService.AyahData GetAyahById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAyahsService/GetIdByName", ReplyAction="http://tempuri.org/IAyahsService/GetIdByNameResponse")]
        int GetIdByName(string nama);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAyahsServiceChannel : Bhm.Web.AyahsService.IAyahsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AyahsServiceClient : System.ServiceModel.ClientBase<Bhm.Web.AyahsService.IAyahsService>, Bhm.Web.AyahsService.IAyahsService {
        
        public AyahsServiceClient() {
        }
        
        public AyahsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AyahsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AyahsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AyahsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void InsertAyah(string nama, string pkj, System.DateTime tl, string alamat) {
            base.Channel.InsertAyah(nama, pkj, tl, alamat);
        }
        
        public Bhm.Web.AyahsService.AyahData GetAyahById(int id) {
            return base.Channel.GetAyahById(id);
        }
        
        public int GetIdByName(string nama) {
            return base.Channel.GetIdByName(nama);
        }
    }
}
