//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhm.Web.ImunisasisService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImunisasiData", Namespace="http://schemas.datacontract.org/2004/07/Imunisasis")]
    [System.SerializableAttribute()]
    public partial class ImunisasiData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime bcg_Polio1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime campakField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dptHb1_Polio2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dptHb2_Polio2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dptHb3_Polio4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime hboField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idImunisasiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime bcg_Polio1 {
            get {
                return this.bcg_Polio1Field;
            }
            set {
                if ((this.bcg_Polio1Field.Equals(value) != true)) {
                    this.bcg_Polio1Field = value;
                    this.RaisePropertyChanged("bcg_Polio1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime campak {
            get {
                return this.campakField;
            }
            set {
                if ((this.campakField.Equals(value) != true)) {
                    this.campakField = value;
                    this.RaisePropertyChanged("campak");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dptHb1_Polio2 {
            get {
                return this.dptHb1_Polio2Field;
            }
            set {
                if ((this.dptHb1_Polio2Field.Equals(value) != true)) {
                    this.dptHb1_Polio2Field = value;
                    this.RaisePropertyChanged("dptHb1_Polio2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dptHb2_Polio2 {
            get {
                return this.dptHb2_Polio2Field;
            }
            set {
                if ((this.dptHb2_Polio2Field.Equals(value) != true)) {
                    this.dptHb2_Polio2Field = value;
                    this.RaisePropertyChanged("dptHb2_Polio2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dptHb3_Polio4 {
            get {
                return this.dptHb3_Polio4Field;
            }
            set {
                if ((this.dptHb3_Polio4Field.Equals(value) != true)) {
                    this.dptHb3_Polio4Field = value;
                    this.RaisePropertyChanged("dptHb3_Polio4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime hbo {
            get {
                return this.hboField;
            }
            set {
                if ((this.hboField.Equals(value) != true)) {
                    this.hboField = value;
                    this.RaisePropertyChanged("hbo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idImunisasi {
            get {
                return this.idImunisasiField;
            }
            set {
                if ((this.idImunisasiField.Equals(value) != true)) {
                    this.idImunisasiField = value;
                    this.RaisePropertyChanged("idImunisasi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ImunisasisService.IImunisasisService")]
    public interface IImunisasisService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImunisasisService/InsertImunisasi", ReplyAction="http://tempuri.org/IImunisasisService/InsertImunisasiResponse")]
        void InsertImunisasi(System.DateTime hbo, System.DateTime bcg_Polio1, System.DateTime dptHb1_Polio2, System.DateTime dptHb2_Polio2, System.DateTime dptHb3_Polio4, System.DateTime campak);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImunisasisService/GetImunisasiById", ReplyAction="http://tempuri.org/IImunisasisService/GetImunisasiByIdResponse")]
        Bhm.Web.ImunisasisService.ImunisasiData GetImunisasiById(int idImunisasi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImunisasisService/UpdateImunisasi", ReplyAction="http://tempuri.org/IImunisasisService/UpdateImunisasiResponse")]
        void UpdateImunisasi(int id, System.DateTime hbo, System.DateTime bcg_Polio1, System.DateTime dptHb1_Polio2, System.DateTime dptHb2_Polio2, System.DateTime dptHb3_Polio4, System.DateTime campak);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IImunisasisServiceChannel : Bhm.Web.ImunisasisService.IImunisasisService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ImunisasisServiceClient : System.ServiceModel.ClientBase<Bhm.Web.ImunisasisService.IImunisasisService>, Bhm.Web.ImunisasisService.IImunisasisService {
        
        public ImunisasisServiceClient() {
        }
        
        public ImunisasisServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ImunisasisServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImunisasisServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImunisasisServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void InsertImunisasi(System.DateTime hbo, System.DateTime bcg_Polio1, System.DateTime dptHb1_Polio2, System.DateTime dptHb2_Polio2, System.DateTime dptHb3_Polio4, System.DateTime campak) {
            base.Channel.InsertImunisasi(hbo, bcg_Polio1, dptHb1_Polio2, dptHb2_Polio2, dptHb3_Polio4, campak);
        }
        
        public Bhm.Web.ImunisasisService.ImunisasiData GetImunisasiById(int idImunisasi) {
            return base.Channel.GetImunisasiById(idImunisasi);
        }
        
        public void UpdateImunisasi(int id, System.DateTime hbo, System.DateTime bcg_Polio1, System.DateTime dptHb1_Polio2, System.DateTime dptHb2_Polio2, System.DateTime dptHb3_Polio4, System.DateTime campak) {
            base.Channel.UpdateImunisasi(id, hbo, bcg_Polio1, dptHb1_Polio2, dptHb2_Polio2, dptHb3_Polio4, campak);
        }
    }
}
