//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("DbBhmModel", "FK_Balita_PunyaAyah_Ayah", "Ayah", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Bhm.Model.Ayah), "Balita", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Bhm.Model.Balita), true)]
[assembly: EdmRelationshipAttribute("DbBhmModel", "FK_Balita_DapatImunisasi_Imunisasi", "Imunisasi", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Bhm.Model.Imunisasi), "Balita", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Bhm.Model.Balita), true)]
[assembly: EdmRelationshipAttribute("DbBhmModel", "FK_Balita_DapatVitamin_Vitamin", "Vitamin", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Bhm.Model.Vitamin), "Balita", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Bhm.Model.Balita), true)]
[assembly: EdmRelationshipAttribute("DbBhmModel", "FK_Balita_PunyaIbu_Ibu", "Ibu", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Bhm.Model.Ibu), "Balita", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Bhm.Model.Balita), true)]
[assembly: EdmRelationshipAttribute("DbBhmModel", "FK_Kegiatan_IkutKegiatan_Balita", "Balita", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Bhm.Model.Balita), "Kegiatan", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Bhm.Model.Kegiatan), true)]
[assembly: EdmRelationshipAttribute("DbBhmModel", "FK_Kegiatan_Diselenggarakan_Posyandu", "Posyandu", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Bhm.Model.Posyandu), "Kegiatan", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Bhm.Model.Kegiatan), true)]

#endregion

namespace Bhm.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DbBhmEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DbBhmEntities object using the connection string found in the 'DbBhmEntities' section of the application configuration file.
        /// </summary>
        public DbBhmEntities() : base("name=DbBhmEntities", "DbBhmEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DbBhmEntities object.
        /// </summary>
        public DbBhmEntities(string connectionString) : base(connectionString, "DbBhmEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DbBhmEntities object.
        /// </summary>
        public DbBhmEntities(EntityConnection connection) : base(connection, "DbBhmEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Ayah> Ayahs
        {
            get
            {
                if ((_Ayahs == null))
                {
                    _Ayahs = base.CreateObjectSet<Ayah>("Ayahs");
                }
                return _Ayahs;
            }
        }
        private ObjectSet<Ayah> _Ayahs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Balita> Balitas
        {
            get
            {
                if ((_Balitas == null))
                {
                    _Balitas = base.CreateObjectSet<Balita>("Balitas");
                }
                return _Balitas;
            }
        }
        private ObjectSet<Balita> _Balitas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Ibu> Ibus
        {
            get
            {
                if ((_Ibus == null))
                {
                    _Ibus = base.CreateObjectSet<Ibu>("Ibus");
                }
                return _Ibus;
            }
        }
        private ObjectSet<Ibu> _Ibus;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Imunisasi> Imunisasis
        {
            get
            {
                if ((_Imunisasis == null))
                {
                    _Imunisasis = base.CreateObjectSet<Imunisasi>("Imunisasis");
                }
                return _Imunisasis;
            }
        }
        private ObjectSet<Imunisasi> _Imunisasis;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Kegiatan> Kegiatans
        {
            get
            {
                if ((_Kegiatans == null))
                {
                    _Kegiatans = base.CreateObjectSet<Kegiatan>("Kegiatans");
                }
                return _Kegiatans;
            }
        }
        private ObjectSet<Kegiatan> _Kegiatans;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Pegawai> Pegawais
        {
            get
            {
                if ((_Pegawais == null))
                {
                    _Pegawais = base.CreateObjectSet<Pegawai>("Pegawais");
                }
                return _Pegawais;
            }
        }
        private ObjectSet<Pegawai> _Pegawais;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Posyandu> Posyandus
        {
            get
            {
                if ((_Posyandus == null))
                {
                    _Posyandus = base.CreateObjectSet<Posyandu>("Posyandus");
                }
                return _Posyandus;
            }
        }
        private ObjectSet<Posyandu> _Posyandus;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Vitamin> Vitamins
        {
            get
            {
                if ((_Vitamins == null))
                {
                    _Vitamins = base.CreateObjectSet<Vitamin>("Vitamins");
                }
                return _Vitamins;
            }
        }
        private ObjectSet<Vitamin> _Vitamins;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Ayahs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAyahs(Ayah ayah)
        {
            base.AddObject("Ayahs", ayah);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Balitas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBalitas(Balita balita)
        {
            base.AddObject("Balitas", balita);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Ibus EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToIbus(Ibu ibu)
        {
            base.AddObject("Ibus", ibu);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Imunisasis EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToImunisasis(Imunisasi imunisasi)
        {
            base.AddObject("Imunisasis", imunisasi);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Kegiatans EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToKegiatans(Kegiatan kegiatan)
        {
            base.AddObject("Kegiatans", kegiatan);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Pegawais EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPegawais(Pegawai pegawai)
        {
            base.AddObject("Pegawais", pegawai);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Posyandus EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPosyandus(Posyandu posyandu)
        {
            base.AddObject("Posyandus", posyandu);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Vitamins EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVitamins(Vitamin vitamin)
        {
            base.AddObject("Vitamins", vitamin);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DbBhmModel", Name="Ayah")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Ayah : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Ayah object.
        /// </summary>
        /// <param name="idAyah">Initial value of the idAyah property.</param>
        public static Ayah CreateAyah(global::System.Int32 idAyah)
        {
            Ayah ayah = new Ayah();
            ayah.idAyah = idAyah;
            return ayah;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idAyah
        {
            get
            {
                return _idAyah;
            }
            set
            {
                if (_idAyah != value)
                {
                    OnidAyahChanging(value);
                    ReportPropertyChanging("idAyah");
                    _idAyah = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idAyah");
                    OnidAyahChanged();
                }
            }
        }
        private global::System.Int32 _idAyah;
        partial void OnidAyahChanging(global::System.Int32 value);
        partial void OnidAyahChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String namaAyah
        {
            get
            {
                return _namaAyah;
            }
            set
            {
                OnnamaAyahChanging(value);
                ReportPropertyChanging("namaAyah");
                _namaAyah = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("namaAyah");
                OnnamaAyahChanged();
            }
        }
        private global::System.String _namaAyah;
        partial void OnnamaAyahChanging(global::System.String value);
        partial void OnnamaAyahChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String pkjAyah
        {
            get
            {
                return _pkjAyah;
            }
            set
            {
                OnpkjAyahChanging(value);
                ReportPropertyChanging("pkjAyah");
                _pkjAyah = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("pkjAyah");
                OnpkjAyahChanged();
            }
        }
        private global::System.String _pkjAyah;
        partial void OnpkjAyahChanging(global::System.String value);
        partial void OnpkjAyahChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> tlAyah
        {
            get
            {
                return _tlAyah;
            }
            set
            {
                OntlAyahChanging(value);
                ReportPropertyChanging("tlAyah");
                _tlAyah = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tlAyah");
                OntlAyahChanged();
            }
        }
        private Nullable<global::System.DateTime> _tlAyah;
        partial void OntlAyahChanging(Nullable<global::System.DateTime> value);
        partial void OntlAyahChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String alamatAyah
        {
            get
            {
                return _alamatAyah;
            }
            set
            {
                OnalamatAyahChanging(value);
                ReportPropertyChanging("alamatAyah");
                _alamatAyah = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("alamatAyah");
                OnalamatAyahChanged();
            }
        }
        private global::System.String _alamatAyah;
        partial void OnalamatAyahChanging(global::System.String value);
        partial void OnalamatAyahChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DbBhmModel", "FK_Balita_PunyaAyah_Ayah", "Balita")]
        public EntityCollection<Balita> Balitas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Balita>("DbBhmModel.FK_Balita_PunyaAyah_Ayah", "Balita");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Balita>("DbBhmModel.FK_Balita_PunyaAyah_Ayah", "Balita", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DbBhmModel", Name="Balita")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Balita : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Balita object.
        /// </summary>
        /// <param name="idBalita">Initial value of the idBalita property.</param>
        /// <param name="idAyah">Initial value of the idAyah property.</param>
        /// <param name="idIbu">Initial value of the idIbu property.</param>
        public static Balita CreateBalita(global::System.Int32 idBalita, global::System.Int32 idAyah, global::System.Int32 idIbu)
        {
            Balita balita = new Balita();
            balita.idBalita = idBalita;
            balita.idAyah = idAyah;
            balita.idIbu = idIbu;
            return balita;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idBalita
        {
            get
            {
                return _idBalita;
            }
            set
            {
                if (_idBalita != value)
                {
                    OnidBalitaChanging(value);
                    ReportPropertyChanging("idBalita");
                    _idBalita = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idBalita");
                    OnidBalitaChanged();
                }
            }
        }
        private global::System.Int32 _idBalita;
        partial void OnidBalitaChanging(global::System.Int32 value);
        partial void OnidBalitaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idAyah
        {
            get
            {
                return _idAyah;
            }
            set
            {
                OnidAyahChanging(value);
                ReportPropertyChanging("idAyah");
                _idAyah = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idAyah");
                OnidAyahChanged();
            }
        }
        private global::System.Int32 _idAyah;
        partial void OnidAyahChanging(global::System.Int32 value);
        partial void OnidAyahChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idIbu
        {
            get
            {
                return _idIbu;
            }
            set
            {
                OnidIbuChanging(value);
                ReportPropertyChanging("idIbu");
                _idIbu = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idIbu");
                OnidIbuChanged();
            }
        }
        private global::System.Int32 _idIbu;
        partial void OnidIbuChanging(global::System.Int32 value);
        partial void OnidIbuChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> idVitamin
        {
            get
            {
                return _idVitamin;
            }
            set
            {
                OnidVitaminChanging(value);
                ReportPropertyChanging("idVitamin");
                _idVitamin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idVitamin");
                OnidVitaminChanged();
            }
        }
        private Nullable<global::System.Int32> _idVitamin;
        partial void OnidVitaminChanging(Nullable<global::System.Int32> value);
        partial void OnidVitaminChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> idImunisasi
        {
            get
            {
                return _idImunisasi;
            }
            set
            {
                OnidImunisasiChanging(value);
                ReportPropertyChanging("idImunisasi");
                _idImunisasi = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idImunisasi");
                OnidImunisasiChanged();
            }
        }
        private Nullable<global::System.Int32> _idImunisasi;
        partial void OnidImunisasiChanging(Nullable<global::System.Int32> value);
        partial void OnidImunisasiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String namaBalita
        {
            get
            {
                return _namaBalita;
            }
            set
            {
                OnnamaBalitaChanging(value);
                ReportPropertyChanging("namaBalita");
                _namaBalita = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("namaBalita");
                OnnamaBalitaChanged();
            }
        }
        private global::System.String _namaBalita;
        partial void OnnamaBalitaChanging(global::System.String value);
        partial void OnnamaBalitaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> tlBalita
        {
            get
            {
                return _tlBalita;
            }
            set
            {
                OntlBalitaChanging(value);
                ReportPropertyChanging("tlBalita");
                _tlBalita = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tlBalita");
                OntlBalitaChanged();
            }
        }
        private Nullable<global::System.DateTime> _tlBalita;
        partial void OntlBalitaChanging(Nullable<global::System.DateTime> value);
        partial void OntlBalitaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String alamatBalita
        {
            get
            {
                return _alamatBalita;
            }
            set
            {
                OnalamatBalitaChanging(value);
                ReportPropertyChanging("alamatBalita");
                _alamatBalita = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("alamatBalita");
                OnalamatBalitaChanged();
            }
        }
        private global::System.String _alamatBalita;
        partial void OnalamatBalitaChanging(global::System.String value);
        partial void OnalamatBalitaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> anakKe
        {
            get
            {
                return _anakKe;
            }
            set
            {
                OnanakKeChanging(value);
                ReportPropertyChanging("anakKe");
                _anakKe = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("anakKe");
                OnanakKeChanged();
            }
        }
        private Nullable<global::System.Int32> _anakKe;
        partial void OnanakKeChanging(Nullable<global::System.Int32> value);
        partial void OnanakKeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String jnsKelamin
        {
            get
            {
                return _jnsKelamin;
            }
            set
            {
                OnjnsKelaminChanging(value);
                ReportPropertyChanging("jnsKelamin");
                _jnsKelamin = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("jnsKelamin");
                OnjnsKelaminChanged();
            }
        }
        private global::System.String _jnsKelamin;
        partial void OnjnsKelaminChanging(global::System.String value);
        partial void OnjnsKelaminChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> bbl
        {
            get
            {
                return _bbl;
            }
            set
            {
                OnbblChanging(value);
                ReportPropertyChanging("bbl");
                _bbl = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("bbl");
                OnbblChanged();
            }
        }
        private Nullable<global::System.Double> _bbl;
        partial void OnbblChanging(Nullable<global::System.Double> value);
        partial void OnbblChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> tbl
        {
            get
            {
                return _tbl;
            }
            set
            {
                OntblChanging(value);
                ReportPropertyChanging("tbl");
                _tbl = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tbl");
                OntblChanged();
            }
        }
        private Nullable<global::System.Double> _tbl;
        partial void OntblChanging(Nullable<global::System.Double> value);
        partial void OntblChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DbBhmModel", "FK_Balita_PunyaAyah_Ayah", "Ayah")]
        public Ayah Ayah
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ayah>("DbBhmModel.FK_Balita_PunyaAyah_Ayah", "Ayah").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ayah>("DbBhmModel.FK_Balita_PunyaAyah_Ayah", "Ayah").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Ayah> AyahReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ayah>("DbBhmModel.FK_Balita_PunyaAyah_Ayah", "Ayah");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Ayah>("DbBhmModel.FK_Balita_PunyaAyah_Ayah", "Ayah", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DbBhmModel", "FK_Balita_DapatImunisasi_Imunisasi", "Imunisasi")]
        public Imunisasi Imunisasi
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Imunisasi>("DbBhmModel.FK_Balita_DapatImunisasi_Imunisasi", "Imunisasi").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Imunisasi>("DbBhmModel.FK_Balita_DapatImunisasi_Imunisasi", "Imunisasi").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Imunisasi> ImunisasiReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Imunisasi>("DbBhmModel.FK_Balita_DapatImunisasi_Imunisasi", "Imunisasi");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Imunisasi>("DbBhmModel.FK_Balita_DapatImunisasi_Imunisasi", "Imunisasi", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DbBhmModel", "FK_Balita_DapatVitamin_Vitamin", "Vitamin")]
        public Vitamin Vitamin
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Vitamin>("DbBhmModel.FK_Balita_DapatVitamin_Vitamin", "Vitamin").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Vitamin>("DbBhmModel.FK_Balita_DapatVitamin_Vitamin", "Vitamin").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Vitamin> VitaminReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Vitamin>("DbBhmModel.FK_Balita_DapatVitamin_Vitamin", "Vitamin");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Vitamin>("DbBhmModel.FK_Balita_DapatVitamin_Vitamin", "Vitamin", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DbBhmModel", "FK_Balita_PunyaIbu_Ibu", "Ibu")]
        public Ibu Ibu
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ibu>("DbBhmModel.FK_Balita_PunyaIbu_Ibu", "Ibu").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ibu>("DbBhmModel.FK_Balita_PunyaIbu_Ibu", "Ibu").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Ibu> IbuReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ibu>("DbBhmModel.FK_Balita_PunyaIbu_Ibu", "Ibu");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Ibu>("DbBhmModel.FK_Balita_PunyaIbu_Ibu", "Ibu", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DbBhmModel", "FK_Kegiatan_IkutKegiatan_Balita", "Kegiatan")]
        public EntityCollection<Kegiatan> Kegiatans
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Kegiatan>("DbBhmModel.FK_Kegiatan_IkutKegiatan_Balita", "Kegiatan");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Kegiatan>("DbBhmModel.FK_Kegiatan_IkutKegiatan_Balita", "Kegiatan", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DbBhmModel", Name="Ibu")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Ibu : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Ibu object.
        /// </summary>
        /// <param name="idIbu">Initial value of the idIbu property.</param>
        public static Ibu CreateIbu(global::System.Int32 idIbu)
        {
            Ibu ibu = new Ibu();
            ibu.idIbu = idIbu;
            return ibu;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idIbu
        {
            get
            {
                return _idIbu;
            }
            set
            {
                if (_idIbu != value)
                {
                    OnidIbuChanging(value);
                    ReportPropertyChanging("idIbu");
                    _idIbu = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idIbu");
                    OnidIbuChanged();
                }
            }
        }
        private global::System.Int32 _idIbu;
        partial void OnidIbuChanging(global::System.Int32 value);
        partial void OnidIbuChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String namaIbu
        {
            get
            {
                return _namaIbu;
            }
            set
            {
                OnnamaIbuChanging(value);
                ReportPropertyChanging("namaIbu");
                _namaIbu = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("namaIbu");
                OnnamaIbuChanged();
            }
        }
        private global::System.String _namaIbu;
        partial void OnnamaIbuChanging(global::System.String value);
        partial void OnnamaIbuChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String pkjIbu
        {
            get
            {
                return _pkjIbu;
            }
            set
            {
                OnpkjIbuChanging(value);
                ReportPropertyChanging("pkjIbu");
                _pkjIbu = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("pkjIbu");
                OnpkjIbuChanged();
            }
        }
        private global::System.String _pkjIbu;
        partial void OnpkjIbuChanging(global::System.String value);
        partial void OnpkjIbuChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> tlIbu
        {
            get
            {
                return _tlIbu;
            }
            set
            {
                OntlIbuChanging(value);
                ReportPropertyChanging("tlIbu");
                _tlIbu = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tlIbu");
                OntlIbuChanged();
            }
        }
        private Nullable<global::System.DateTime> _tlIbu;
        partial void OntlIbuChanging(Nullable<global::System.DateTime> value);
        partial void OntlIbuChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String alamatIbu
        {
            get
            {
                return _alamatIbu;
            }
            set
            {
                OnalamatIbuChanging(value);
                ReportPropertyChanging("alamatIbu");
                _alamatIbu = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("alamatIbu");
                OnalamatIbuChanged();
            }
        }
        private global::System.String _alamatIbu;
        partial void OnalamatIbuChanging(global::System.String value);
        partial void OnalamatIbuChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DbBhmModel", "FK_Balita_PunyaIbu_Ibu", "Balita")]
        public EntityCollection<Balita> Balitas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Balita>("DbBhmModel.FK_Balita_PunyaIbu_Ibu", "Balita");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Balita>("DbBhmModel.FK_Balita_PunyaIbu_Ibu", "Balita", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DbBhmModel", Name="Imunisasi")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Imunisasi : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Imunisasi object.
        /// </summary>
        /// <param name="idImunisasi">Initial value of the idImunisasi property.</param>
        public static Imunisasi CreateImunisasi(global::System.Int32 idImunisasi)
        {
            Imunisasi imunisasi = new Imunisasi();
            imunisasi.idImunisasi = idImunisasi;
            return imunisasi;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idImunisasi
        {
            get
            {
                return _idImunisasi;
            }
            set
            {
                if (_idImunisasi != value)
                {
                    OnidImunisasiChanging(value);
                    ReportPropertyChanging("idImunisasi");
                    _idImunisasi = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idImunisasi");
                    OnidImunisasiChanged();
                }
            }
        }
        private global::System.Int32 _idImunisasi;
        partial void OnidImunisasiChanging(global::System.Int32 value);
        partial void OnidImunisasiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> hbo
        {
            get
            {
                return _hbo;
            }
            set
            {
                OnhboChanging(value);
                ReportPropertyChanging("hbo");
                _hbo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("hbo");
                OnhboChanged();
            }
        }
        private Nullable<global::System.DateTime> _hbo;
        partial void OnhboChanging(Nullable<global::System.DateTime> value);
        partial void OnhboChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> bcg_Polio1
        {
            get
            {
                return _bcg_Polio1;
            }
            set
            {
                Onbcg_Polio1Changing(value);
                ReportPropertyChanging("bcg_Polio1");
                _bcg_Polio1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("bcg_Polio1");
                Onbcg_Polio1Changed();
            }
        }
        private Nullable<global::System.DateTime> _bcg_Polio1;
        partial void Onbcg_Polio1Changing(Nullable<global::System.DateTime> value);
        partial void Onbcg_Polio1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> dptHb1_Polio2
        {
            get
            {
                return _dptHb1_Polio2;
            }
            set
            {
                OndptHb1_Polio2Changing(value);
                ReportPropertyChanging("dptHb1_Polio2");
                _dptHb1_Polio2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dptHb1_Polio2");
                OndptHb1_Polio2Changed();
            }
        }
        private Nullable<global::System.DateTime> _dptHb1_Polio2;
        partial void OndptHb1_Polio2Changing(Nullable<global::System.DateTime> value);
        partial void OndptHb1_Polio2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> dptHb2_Polio2
        {
            get
            {
                return _dptHb2_Polio2;
            }
            set
            {
                OndptHb2_Polio2Changing(value);
                ReportPropertyChanging("dptHb2_Polio2");
                _dptHb2_Polio2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dptHb2_Polio2");
                OndptHb2_Polio2Changed();
            }
        }
        private Nullable<global::System.DateTime> _dptHb2_Polio2;
        partial void OndptHb2_Polio2Changing(Nullable<global::System.DateTime> value);
        partial void OndptHb2_Polio2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> dptHb3_Polio4
        {
            get
            {
                return _dptHb3_Polio4;
            }
            set
            {
                OndptHb3_Polio4Changing(value);
                ReportPropertyChanging("dptHb3_Polio4");
                _dptHb3_Polio4 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dptHb3_Polio4");
                OndptHb3_Polio4Changed();
            }
        }
        private Nullable<global::System.DateTime> _dptHb3_Polio4;
        partial void OndptHb3_Polio4Changing(Nullable<global::System.DateTime> value);
        partial void OndptHb3_Polio4Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> campak
        {
            get
            {
                return _campak;
            }
            set
            {
                OncampakChanging(value);
                ReportPropertyChanging("campak");
                _campak = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("campak");
                OncampakChanged();
            }
        }
        private Nullable<global::System.DateTime> _campak;
        partial void OncampakChanging(Nullable<global::System.DateTime> value);
        partial void OncampakChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DbBhmModel", "FK_Balita_DapatImunisasi_Imunisasi", "Balita")]
        public EntityCollection<Balita> Balitas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Balita>("DbBhmModel.FK_Balita_DapatImunisasi_Imunisasi", "Balita");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Balita>("DbBhmModel.FK_Balita_DapatImunisasi_Imunisasi", "Balita", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DbBhmModel", Name="Kegiatan")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Kegiatan : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Kegiatan object.
        /// </summary>
        /// <param name="idKeg">Initial value of the idKeg property.</param>
        /// <param name="idPosyandu">Initial value of the idPosyandu property.</param>
        /// <param name="idBalita">Initial value of the idBalita property.</param>
        public static Kegiatan CreateKegiatan(global::System.Int32 idKeg, global::System.Int32 idPosyandu, global::System.Int32 idBalita)
        {
            Kegiatan kegiatan = new Kegiatan();
            kegiatan.idKeg = idKeg;
            kegiatan.idPosyandu = idPosyandu;
            kegiatan.idBalita = idBalita;
            return kegiatan;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idKeg
        {
            get
            {
                return _idKeg;
            }
            set
            {
                if (_idKeg != value)
                {
                    OnidKegChanging(value);
                    ReportPropertyChanging("idKeg");
                    _idKeg = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idKeg");
                    OnidKegChanged();
                }
            }
        }
        private global::System.Int32 _idKeg;
        partial void OnidKegChanging(global::System.Int32 value);
        partial void OnidKegChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idPosyandu
        {
            get
            {
                return _idPosyandu;
            }
            set
            {
                OnidPosyanduChanging(value);
                ReportPropertyChanging("idPosyandu");
                _idPosyandu = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idPosyandu");
                OnidPosyanduChanged();
            }
        }
        private global::System.Int32 _idPosyandu;
        partial void OnidPosyanduChanging(global::System.Int32 value);
        partial void OnidPosyanduChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idBalita
        {
            get
            {
                return _idBalita;
            }
            set
            {
                OnidBalitaChanging(value);
                ReportPropertyChanging("idBalita");
                _idBalita = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idBalita");
                OnidBalitaChanged();
            }
        }
        private global::System.Int32 _idBalita;
        partial void OnidBalitaChanging(global::System.Int32 value);
        partial void OnidBalitaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> tglPeriksa
        {
            get
            {
                return _tglPeriksa;
            }
            set
            {
                OntglPeriksaChanging(value);
                ReportPropertyChanging("tglPeriksa");
                _tglPeriksa = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tglPeriksa");
                OntglPeriksaChanged();
            }
        }
        private Nullable<global::System.DateTime> _tglPeriksa;
        partial void OntglPeriksaChanging(Nullable<global::System.DateTime> value);
        partial void OntglPeriksaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> bb
        {
            get
            {
                return _bb;
            }
            set
            {
                OnbbChanging(value);
                ReportPropertyChanging("bb");
                _bb = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("bb");
                OnbbChanged();
            }
        }
        private Nullable<global::System.Double> _bb;
        partial void OnbbChanging(Nullable<global::System.Double> value);
        partial void OnbbChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> tb
        {
            get
            {
                return _tb;
            }
            set
            {
                OntbChanging(value);
                ReportPropertyChanging("tb");
                _tb = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tb");
                OntbChanged();
            }
        }
        private Nullable<global::System.Double> _tb;
        partial void OntbChanging(Nullable<global::System.Double> value);
        partial void OntbChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DbBhmModel", "FK_Kegiatan_IkutKegiatan_Balita", "Balita")]
        public Balita Balita
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Balita>("DbBhmModel.FK_Kegiatan_IkutKegiatan_Balita", "Balita").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Balita>("DbBhmModel.FK_Kegiatan_IkutKegiatan_Balita", "Balita").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Balita> BalitaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Balita>("DbBhmModel.FK_Kegiatan_IkutKegiatan_Balita", "Balita");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Balita>("DbBhmModel.FK_Kegiatan_IkutKegiatan_Balita", "Balita", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DbBhmModel", "FK_Kegiatan_Diselenggarakan_Posyandu", "Posyandu")]
        public Posyandu Posyandu
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Posyandu>("DbBhmModel.FK_Kegiatan_Diselenggarakan_Posyandu", "Posyandu").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Posyandu>("DbBhmModel.FK_Kegiatan_Diselenggarakan_Posyandu", "Posyandu").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Posyandu> PosyanduReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Posyandu>("DbBhmModel.FK_Kegiatan_Diselenggarakan_Posyandu", "Posyandu");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Posyandu>("DbBhmModel.FK_Kegiatan_Diselenggarakan_Posyandu", "Posyandu", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DbBhmModel", Name="Pegawai")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Pegawai : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Pegawai object.
        /// </summary>
        /// <param name="idPgw">Initial value of the idPgw property.</param>
        /// <param name="isAdmin">Initial value of the isAdmin property.</param>
        public static Pegawai CreatePegawai(global::System.Int32 idPgw, global::System.Boolean isAdmin)
        {
            Pegawai pegawai = new Pegawai();
            pegawai.idPgw = idPgw;
            pegawai.isAdmin = isAdmin;
            return pegawai;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idPgw
        {
            get
            {
                return _idPgw;
            }
            set
            {
                if (_idPgw != value)
                {
                    OnidPgwChanging(value);
                    ReportPropertyChanging("idPgw");
                    _idPgw = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idPgw");
                    OnidPgwChanged();
                }
            }
        }
        private global::System.Int32 _idPgw;
        partial void OnidPgwChanging(global::System.Int32 value);
        partial void OnidPgwChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String namaPgw
        {
            get
            {
                return _namaPgw;
            }
            set
            {
                OnnamaPgwChanging(value);
                ReportPropertyChanging("namaPgw");
                _namaPgw = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("namaPgw");
                OnnamaPgwChanged();
            }
        }
        private global::System.String _namaPgw;
        partial void OnnamaPgwChanging(global::System.String value);
        partial void OnnamaPgwChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String instansi
        {
            get
            {
                return _instansi;
            }
            set
            {
                OninstansiChanging(value);
                ReportPropertyChanging("instansi");
                _instansi = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("instansi");
                OninstansiChanged();
            }
        }
        private global::System.String _instansi;
        partial void OninstansiChanging(global::System.String value);
        partial void OninstansiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String usernamePgw
        {
            get
            {
                return _usernamePgw;
            }
            set
            {
                OnusernamePgwChanging(value);
                ReportPropertyChanging("usernamePgw");
                _usernamePgw = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("usernamePgw");
                OnusernamePgwChanged();
            }
        }
        private global::System.String _usernamePgw;
        partial void OnusernamePgwChanging(global::System.String value);
        partial void OnusernamePgwChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String passwordPgw
        {
            get
            {
                return _passwordPgw;
            }
            set
            {
                OnpasswordPgwChanging(value);
                ReportPropertyChanging("passwordPgw");
                _passwordPgw = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("passwordPgw");
                OnpasswordPgwChanged();
            }
        }
        private global::System.String _passwordPgw;
        partial void OnpasswordPgwChanging(global::System.String value);
        partial void OnpasswordPgwChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean isAdmin
        {
            get
            {
                return _isAdmin;
            }
            set
            {
                OnisAdminChanging(value);
                ReportPropertyChanging("isAdmin");
                _isAdmin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isAdmin");
                OnisAdminChanged();
            }
        }
        private global::System.Boolean _isAdmin;
        partial void OnisAdminChanging(global::System.Boolean value);
        partial void OnisAdminChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DbBhmModel", Name="Posyandu")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Posyandu : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Posyandu object.
        /// </summary>
        /// <param name="idPosyandu">Initial value of the idPosyandu property.</param>
        public static Posyandu CreatePosyandu(global::System.Int32 idPosyandu)
        {
            Posyandu posyandu = new Posyandu();
            posyandu.idPosyandu = idPosyandu;
            return posyandu;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idPosyandu
        {
            get
            {
                return _idPosyandu;
            }
            set
            {
                if (_idPosyandu != value)
                {
                    OnidPosyanduChanging(value);
                    ReportPropertyChanging("idPosyandu");
                    _idPosyandu = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idPosyandu");
                    OnidPosyanduChanged();
                }
            }
        }
        private global::System.Int32 _idPosyandu;
        partial void OnidPosyanduChanging(global::System.Int32 value);
        partial void OnidPosyanduChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String namaPosyandu
        {
            get
            {
                return _namaPosyandu;
            }
            set
            {
                OnnamaPosyanduChanging(value);
                ReportPropertyChanging("namaPosyandu");
                _namaPosyandu = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("namaPosyandu");
                OnnamaPosyanduChanged();
            }
        }
        private global::System.String _namaPosyandu;
        partial void OnnamaPosyanduChanging(global::System.String value);
        partial void OnnamaPosyanduChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String desaPosyandu
        {
            get
            {
                return _desaPosyandu;
            }
            set
            {
                OndesaPosyanduChanging(value);
                ReportPropertyChanging("desaPosyandu");
                _desaPosyandu = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("desaPosyandu");
                OndesaPosyanduChanged();
            }
        }
        private global::System.String _desaPosyandu;
        partial void OndesaPosyanduChanging(global::System.String value);
        partial void OndesaPosyanduChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String kecPosyandu
        {
            get
            {
                return _kecPosyandu;
            }
            set
            {
                OnkecPosyanduChanging(value);
                ReportPropertyChanging("kecPosyandu");
                _kecPosyandu = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("kecPosyandu");
                OnkecPosyanduChanged();
            }
        }
        private global::System.String _kecPosyandu;
        partial void OnkecPosyanduChanging(global::System.String value);
        partial void OnkecPosyanduChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String kabPosyandu
        {
            get
            {
                return _kabPosyandu;
            }
            set
            {
                OnkabPosyanduChanging(value);
                ReportPropertyChanging("kabPosyandu");
                _kabPosyandu = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("kabPosyandu");
                OnkabPosyanduChanged();
            }
        }
        private global::System.String _kabPosyandu;
        partial void OnkabPosyanduChanging(global::System.String value);
        partial void OnkabPosyanduChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String provPosyandu
        {
            get
            {
                return _provPosyandu;
            }
            set
            {
                OnprovPosyanduChanging(value);
                ReportPropertyChanging("provPosyandu");
                _provPosyandu = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("provPosyandu");
                OnprovPosyanduChanged();
            }
        }
        private global::System.String _provPosyandu;
        partial void OnprovPosyanduChanging(global::System.String value);
        partial void OnprovPosyanduChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DbBhmModel", "FK_Kegiatan_Diselenggarakan_Posyandu", "Kegiatan")]
        public EntityCollection<Kegiatan> Kegiatans
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Kegiatan>("DbBhmModel.FK_Kegiatan_Diselenggarakan_Posyandu", "Kegiatan");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Kegiatan>("DbBhmModel.FK_Kegiatan_Diselenggarakan_Posyandu", "Kegiatan", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DbBhmModel", Name="Vitamin")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Vitamin : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Vitamin object.
        /// </summary>
        /// <param name="idVitamin">Initial value of the idVitamin property.</param>
        public static Vitamin CreateVitamin(global::System.Int32 idVitamin)
        {
            Vitamin vitamin = new Vitamin();
            vitamin.idVitamin = idVitamin;
            return vitamin;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idVitamin
        {
            get
            {
                return _idVitamin;
            }
            set
            {
                if (_idVitamin != value)
                {
                    OnidVitaminChanging(value);
                    ReportPropertyChanging("idVitamin");
                    _idVitamin = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idVitamin");
                    OnidVitaminChanged();
                }
            }
        }
        private global::System.Int32 _idVitamin;
        partial void OnidVitaminChanging(global::System.Int32 value);
        partial void OnidVitaminChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> kapsulBiru
        {
            get
            {
                return _kapsulBiru;
            }
            set
            {
                OnkapsulBiruChanging(value);
                ReportPropertyChanging("kapsulBiru");
                _kapsulBiru = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("kapsulBiru");
                OnkapsulBiruChanged();
            }
        }
        private Nullable<global::System.DateTime> _kapsulBiru;
        partial void OnkapsulBiruChanging(Nullable<global::System.DateTime> value);
        partial void OnkapsulBiruChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> kapsulMerah1
        {
            get
            {
                return _kapsulMerah1;
            }
            set
            {
                OnkapsulMerah1Changing(value);
                ReportPropertyChanging("kapsulMerah1");
                _kapsulMerah1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("kapsulMerah1");
                OnkapsulMerah1Changed();
            }
        }
        private Nullable<global::System.DateTime> _kapsulMerah1;
        partial void OnkapsulMerah1Changing(Nullable<global::System.DateTime> value);
        partial void OnkapsulMerah1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> kapsulMerah2
        {
            get
            {
                return _kapsulMerah2;
            }
            set
            {
                OnkapsulMerah2Changing(value);
                ReportPropertyChanging("kapsulMerah2");
                _kapsulMerah2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("kapsulMerah2");
                OnkapsulMerah2Changed();
            }
        }
        private Nullable<global::System.DateTime> _kapsulMerah2;
        partial void OnkapsulMerah2Changing(Nullable<global::System.DateTime> value);
        partial void OnkapsulMerah2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> kapsulMerah3
        {
            get
            {
                return _kapsulMerah3;
            }
            set
            {
                OnkapsulMerah3Changing(value);
                ReportPropertyChanging("kapsulMerah3");
                _kapsulMerah3 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("kapsulMerah3");
                OnkapsulMerah3Changed();
            }
        }
        private Nullable<global::System.DateTime> _kapsulMerah3;
        partial void OnkapsulMerah3Changing(Nullable<global::System.DateTime> value);
        partial void OnkapsulMerah3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> kapsulMerah4
        {
            get
            {
                return _kapsulMerah4;
            }
            set
            {
                OnkapsulMerah4Changing(value);
                ReportPropertyChanging("kapsulMerah4");
                _kapsulMerah4 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("kapsulMerah4");
                OnkapsulMerah4Changed();
            }
        }
        private Nullable<global::System.DateTime> _kapsulMerah4;
        partial void OnkapsulMerah4Changing(Nullable<global::System.DateTime> value);
        partial void OnkapsulMerah4Changed();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DbBhmModel", "FK_Balita_DapatVitamin_Vitamin", "Balita")]
        public EntityCollection<Balita> Balitas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Balita>("DbBhmModel.FK_Balita_DapatVitamin_Vitamin", "Balita");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Balita>("DbBhmModel.FK_Balita_DapatVitamin_Vitamin", "Balita", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
